"""
DEPRECATED — createRenderInfo.py

This module previously generated renderInstructions.json from ADM intermediate data.
As of v0.5.1, the LUSID scene (scene.lusid.json) is the canonical spatial data format
and is generated by LUSID/src/xmlParser.py.

The original implementation is preserved at:
    src/packageADM/old_schema/createRenderInfo.py

The pipeline now uses:
    from LUSID.src.xmlParser import load_processed_data_and_build_scene

See LUSID/internalDocs/DEVELOPMENT.md for architecture details.
"""

import warnings


def createRenderInfoJSON(processed_dir="processedData", output_path=None):
    """DEPRECATED: Use LUSID xmlParser instead.
    
    This function is kept only for backward compatibility. It raises a
    deprecation warning and delegates to the LUSID scene builder.
    """
    warnings.warn(
        "createRenderInfoJSON() is deprecated. "
        "The pipeline now uses LUSID/src/xmlParser.py to generate scene.lusid.json. "
        "See LUSID/internalDocs/DEVELOPMENT.md.",
        DeprecationWarning,
        stacklevel=2,
    )
    from LUSID.src.xmlParser import load_processed_data_and_build_scene

    lusid_output = f"{processed_dir}/stageForRender/scene.lusid.json"
    scene = load_processed_data_and_build_scene(
        processed_dir=processed_dir,
        output_path=lusid_output,
    )
    return scene
